In [1]:
import os, cv2
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [2]:
BASE_DIR = 'D:/Arthur_Noh/Lab/IDG_image/train'
CATEGORIES = ['blackice', 'dry', 'wet', 'snow']
nb_classes = len(CATEGORIES)

IMAGE_SIZE = 150

X = []
Y = []

In [3]:
for idx, category in enumerate(CATEGORIES):
    # one-hot incoding
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    
    path = os.path.join(BASE_DIR, category)
    # check to see if read images work
    print(category, '의 파일 길이 : ', len(os.listdir(path)))
    
    for i, image in enumerate(os.listdir(path)):
        img = cv2.imread(os.path.join(path, image),
                        cv2.IMREAD_COLOR)
        
        # Convert cv2 BRG image to RGB image
        b, g, r = cv2.split(img)
        img = cv2.merge([r, g, b])
        
        # Make image size that we want
        img = cv2.resize(img, (IMAGE_SIZE, IMAGE_SIZE))
        data = np.array(img)
        
        # input data in temp variable
        X.append(data)
        Y.append(label)
        
        # check image lists
        if i % 1000 == 0:
            print(category, ':', image)
    print('\n')

blackice 의 파일 길이 :  4500
blackice : 03491.jpg
blackice : 00363.jpg
blackice : 03165.jpg
blackice : 01553.jpg
blackice : 02553.jpg


dry 의 파일 길이 :  4500
dry : 04500.jpg
dry : 01000.jpg
dry : 02000.jpg
dry : 03000.jpg
dry : 04000.jpg


wet 의 파일 길이 :  4500
wet : 04500.jpg
wet : 01000.jpg
wet : 02000.jpg
wet : 03000.jpg
wet : 04000.jpg


snow 의 파일 길이 :  4500
snow : 04500.jpg
snow : 01000.jpg
snow : 02000.jpg
snow : 03000.jpg
snow : 04000.jpg




In [4]:
# Exam
# 1 0 0 0 == blackice
# 0 1 0 0 == dry

X = np.array(X)
Y = np.array(Y)

In [5]:
print('Data length(X) : ', len(X))
print('Data length(Y) : ', len(Y))

Data length(X) :  18000
Data length(Y) :  18000


In [6]:
X.dtype

dtype('uint8')

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [8]:
print(X_train[1])

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [9]:
# generalization
X_train = X_train.astype('float16') / 255.0
X_test = X_test.astype('float16') / 255.0

In [10]:
xy = (X_train, X_test, y_train, y_test)
# Code has error
# Error
# [OverflowError: cannot serialize a bytes object larger than 4 GiB]
# np.save('./Black_ice_Detection.npy', xy)

# So i use pickle, protocol=4
import pickle
pickle.dump(xy, open("Black_ice_Detection.npy", 'wb'), protocol=4)